/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 0588350abbb82f70ebe13bb57f6b9415)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		OPENAI_API_KEY: string;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		AI: Ai;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		GOOGLE_REDIRECT_URI: string;
		DISCORD_TOKEN: string;
		TELEGRAM_TOKEN: string;
		SLACK_TOKEN: string;
		DISCORD_PUBLIC_KEY: string;
		GEMINI_API_KEY: string;
	}
}
interface Env extends Cloudflare.Env { }
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY" | "GEMINI_API_KEY" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "GOOGLE_REDIRECT_URI" | "DISCORD_TOKEN" | "TELEGRAM_TOKEN" | "SLACK_TOKEN">> { }
}
